export const page = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Model Providers</title><style>body{font:14px system-ui;margin:0;background:#10141c;color:#e8edf5}main{max-width:1180px;margin:auto;padding:24px}section,.dialog{background:#181f2b;border:1px solid #2b3748;border-radius:10px;padding:18px;margin:14px 0}button,input{padding:9px;border-radius:6px;border:1px solid #46556b;background:#111722;color:inherit;margin:3px}button{cursor:pointer;background:#285ea8}.muted{color:#94a3b8}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:8px;border-bottom:1px solid #2b3748}.modal{position:fixed;inset:0;background:#0009;display:none;align-items:center;justify-content:center}.dialog{width:min(620px,90vw)}.dialog input{box-sizing:border-box;width:100%;margin:6px 0}pre{white-space:pre-wrap;max-height:360px;overflow:auto}@media(max-width:700px){main{padding:10px}table{font-size:12px}}</style></head><body><main><h1>Model Providers</h1><div id="status" class="muted"></div><section><button id="add">添加 Provider</button><table><thead><tr><th>Provider</th><th>URL</th><th>模型</th><th>优先级</th><th>状态</th><th>操作</th></tr></thead><tbody id="providers"></tbody></table></section></main><div id="modal" class="modal"><form id="provider" class="dialog"><h2 id="title"></h2><input name="name" placeholder="名称（可选）"><input name="baseUrl" placeholder="Base URL，例如 https://api.example.com/v1" required><input name="apiKey" type="password" placeholder="API Key（编辑时留空表示不修改）"><input name="model" placeholder="模型覆盖（可选）"><input name="priority" type="number" min="0" placeholder="优先级（默认 100）"><button>保存</button><button id="cancel" type="button">取消</button></form></div><div id="info" class="modal"><div class="dialog"><h2 id="infoTitle"></h2><pre id="infoBody"></pre><button id="infoClose" type="button">关闭</button></div></div><script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let data=[];const $=s=>document.querySelector(s),form=$('#provider'),modal=$('#modal'),info=$('#info');
function makeLog(title,id){const section=document.createElement('section'),heading=document.createElement('h2'),target=document.createElement('div');heading.textContent=title;target.id=id;target.className='log';target.style.cssText='height:220px;overflow:auto;background:#080b10;color:#a7f3d0;padding:8px;font:12px ui-monospace,monospace';section.append(heading,target);document.querySelector('main').append(section)}
function logKey(item){return item.at+'|'+item.requestId+'|'+item.direction+'|'+item.type+'|'+item.providerId+'|'+item.status}
function logNode(item){const details=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre');details.dataset.key=logKey(item);summary.textContent=item.at+' '+item.type+' '+(item.providerName?'['+item.providerName+'] ':'')+(item.method||'')+' '+(item.path||'')+' '+(item.status||'');pre.textContent=JSON.stringify(item,null,2);details.append(summary,pre);return details}
function renderLogs(target,items){const atBottom=target.scrollHeight-target.scrollTop-target.clientHeight<12;const previous=new Map([...target.children].map(node=>[node.dataset.key,node]));const wanted=new Set(items.map(logKey));for(const node of [...target.children])if(!wanted.has(node.dataset.key))node.remove();for(const [index,item] of items.entries()){const key=logKey(item),node=previous.get(key)||logNode(item),current=target.children[index];if(!previous.has(key))target.insertBefore(node,current||null);if(current!==node)target.insertBefore(node,current||null)}if(atBottom)target.scrollTop=target.scrollHeight}
async function loadLogs(){const result=await (await fetch('/admin/logs')).json();renderLogs($('#downstreamLog'),result.downstream);renderLogs($('#upstreamLog'),result.upstream)}
async function load(){const r=await fetch('/admin/providers');data=await r.json();$('#providers').replaceChildren(...(data.length?data.map(x=>{const tr=document.createElement('tr'),h=x.health,model=x.model||((x.probeModel)?'透传：'+x.probeModel:'透传');tr.innerHTML='<td>'+esc(x.name)+'</td><td>'+esc(x.baseUrl)+'</td><td>'+esc(model)+'</td><td>'+x.priority+'</td><td>'+esc(h?.status||'unknown')+'<br><span class="muted">'+esc(countdown(h))+'</span></td><td></td>';const cell=tr.lastElementChild;[['模型',showModels],['探测',probe],['历史',showHistory],['编辑',id=>openProvider(data.find(p=>p.id===id))],['删除',removeProvider]].forEach(([label,fn])=>{const b=document.createElement('button');b.textContent=label;b.dataset.id=x.id;b.addEventListener('click',()=>fn(b.dataset.id));cell.append(b)});return tr}):[Object.assign(document.createElement('tr'),{innerHTML:'<td colspan="6">暂无 Provider</td>'})]));$('#status').textContent='已配置 '+data.length+' 个 Provider'}
function countdown(health){if(!health)return '未探测';if(health.nextProbeAt&&health.nextProbeAt>Date.now()){const seconds=Math.ceil((health.nextProbeAt-Date.now())/1000);return '冷却，距下次探测 '+Math.floor(seconds/60)+'分'+String(seconds%60).padStart(2,'0')+'秒'}return health.status==='cooldown'?'可探测':health.status||'未探测'}
function openProvider(x){form.dataset.id=x?.id||'';for(const k of ['name','baseUrl','model'])form.elements[k].value=x?.[k]||'';form.elements.apiKey.value='';form.elements.priority.value=x&&x.priority!==100?x.priority:'';$('#title').textContent=x?'编辑 Provider':'添加 Provider';modal.style.display='flex'}
function closeDialog(){modal.style.display='none'}
async function removeProvider(id){if(confirm('删除此 Provider？')){await fetch('/admin/providers/'+encodeURIComponent(id),{method:'DELETE'});load()}}
async function showModels(id,refresh=true){const r=await fetch('/admin/providers/'+encodeURIComponent(id)+'/models'+(refresh?'?refresh=1':'')),x=await r.json();$('#infoTitle').textContent='模型列表';$('#infoBody').textContent=r.ok?'刷新时间: '+x.refreshedAt+'\\n\\n'+x.models.map(m=>m.id).join('\\n'):(x.error||'模型读取失败');const button=document.createElement('button');button.textContent='刷新模型';button.addEventListener('click',()=>showModels(id,true));$('#infoBody').after(button);info.style.display='flex'}
async function showHistory(id){const x=await(await fetch('/admin/providers/'+encodeURIComponent(id)+'/history')).json();$('#infoTitle').textContent='通信历史';$('#infoBody').textContent=x.length?x.map(item=>[item.at,item.providerName||item.providerId,item.operation,item.model||'',item.result||'',item.status||'',item.durationMs===undefined?'':item.durationMs+'ms'].join('  ')).join('\\n'):'暂无通信历史';info.style.display='flex'}
async function probe(id){const r=await fetch('/admin/providers/'+encodeURIComponent(id)+'/probe',{method:'POST'});if(!r.ok)alert((await r.json()).error||'探测失败');load()}
$('#add').addEventListener('click',()=>openProvider());$('#cancel').addEventListener('click',closeDialog);$('#infoClose').addEventListener('click',()=>info.style.display='none');form.addEventListener('submit',async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(form)),id=form.dataset.id;for(const k of ['name','model','apiKey','priority'])if(!x[k])delete x[k];if(x.priority)x.priority=Number(x.priority);if(!id)x.id='provider_'+Date.now();const r=await fetch(id?'/admin/providers/'+encodeURIComponent(id):'/admin/providers',{method:id?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(x)});if(!r.ok)return alert((await r.json()).error||'保存失败');closeDialog();load()});document.addEventListener('DOMContentLoaded',()=>{makeLog('下游通信日志','downstreamLog');makeLog('上游通信日志','upstreamLog');load();loadLogs();setInterval(()=>{load();loadLogs()},1000)});
</script></body></html>`
